server:
  port: 8082

spring:
  application:
    name: customerservice

  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 200ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  mongodb:
    uri: mongodb://localhost:27016/customerdb

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
      key-prefix: "customer::"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce
          jwk-set-uri: http://localhost:8080/realms/ecommerce/protocol/openid-connect/certs


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ecommerce.customerservice: DEBUG
